# Exercise 1: Build the CSVReader Class (OOP Foundation)

### Objective:
- Reinforce OOP fundamentals: classes, constructors, methods, encapsulation.
- Learn to design reusable data classes for Data Science projects.

### Concept:
A `CSVReader` class encapsulates all functionality related to reading and inspecting CSV files.
Instead of calling `pd.read_csv()` repeatedly in different scripts, we wrap the loading logic in a reusable class.

## 1. Defining the CSVReader Class

We implement the `CSVReader` class with:
- `__init__(self, file_path)`: Stores the path to the CSV file and initializes `self.data` as `None`.
- `read(self)`: Reads the CSV file using pandas and stores the DataFrame inside `self.data`.
- `preview(self, n=5)`: Displays the top `n` rows of the loaded DataFrame.

In [1]:
import pandas as pd

class CSVReader:
    """
    A reusable class to load and preview CSV files.
    """
    def __init__(self, file_path: str):
        # Store the path to the CSV file
        self.file_path = file_path
        # Initially, no data is loaded
        self.data = None
    
    def read(self):
        """Loads the CSV file using pandas."""
        print(f"Loading data from: {self.file_path}")
        self.data = pd.read_csv(self.file_path)
        print("Data loaded successfully!")
        return self.data
    
    def preview(self, n: int = 5):
        """Prints the top n rows of the loaded DataFrame."""
        if self.data is None:
            print("Warning: No data loaded yet. Please call read() first.")
            return None
        
        print(f"--- Previewing top {n} rows ---")
        return self.data.head(n)

## 2. Testing the CSVReader Class

Let's test our `CSVReader` using our sample dataset `sample_data.csv`.

In [2]:
# Instantiate the reader with the path to our sample CSV
csv_reader = CSVReader("sample_data.csv")

# Try previewing before reading (to check safety check)
csv_reader.preview()

Warning: No data loaded yet. Please call read() first.

In [3]:
# Now read the file
df = csv_reader.read()

# Preview the top 3 rows
csv_reader.preview(3)

Loading data from: sample_data.csv
Data loaded successfully!
--- Previewing top 3 rows ---

   id     name   age   salary      city
0   1    Alice  25.0  50000.0  New York
1   2      Bob  30.0      NaN     Paris
2   3  Charlie   NaN  70000.0    London

In [4]:
# Preview the top 5 rows
csv_reader.preview(5)

--- Previewing top 5 rows ---

   id     name   age   salary      city
0   1    Alice  25.0  50000.0  New York
1   2      Bob  30.0      NaN     Paris
2   3  Charlie   NaN  70000.0    London
3   4    David  40.0  90000.0     TOKYO
4   5    Alice  25.0  50000.0  New York

### Summary:
- Successfully implemented `CSVReader` adhering to OOP encapsulation principles.
- The class holds the state (`self.file_path`, `self.data`) and exposes clear methods (`read`, `preview`).